<?php
/**
 * TEMPLATE — copy to inc/elementor/widgets/class-<slug>-widget.php, rename
 * the class, update get_name()/get_title(), then register it explicitly in
 * functions.php. Do not edit this file in place; it is never loaded.
 *
 * @package {{THEME_NAME}}
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

namespace {{THEME_NAME}}\Widgets;

class Example_Widget extends \Elementor\Widget_Base {

    public function get_name(): string {
        return 'example_widget';
    }

    public function get_title(): string {
        return __( 'Example', '{{THEME_TEXT_DOMAIN}}' );
    }

    public function get_icon(): string {
        return 'eicon-code';
    }

    public function get_categories(): array {
        return array( '{{WIDGET_CATEGORY_SLUG}}' );
    }

    protected function register_controls(): void {
        $this->start_controls_section(
            'content_section',
            array(
                'label' => __( 'Content', '{{THEME_TEXT_DOMAIN}}' ),
                'tab'   => \Elementor\Controls_Manager::TAB_CONTENT,
            )
        );

        $this->add_control(
            'heading',
            array(
                'label'   => __( 'Heading', '{{THEME_TEXT_DOMAIN}}' ),
                'type'    => \Elementor\Controls_Manager::TEXT,
                'default' => __( 'Hello world', '{{THEME_TEXT_DOMAIN}}' ),
            )
        );

        $this->end_controls_section();
    }

    protected function render(): void {
        $settings = $this->get_settings_for_display();
        ?>
        <section class="example-widget">
            <h2><?php echo esc_html( $settings['heading'] ); ?></h2>
        </section>
        <?php
    }
}
